# -*- coding: utf-8 -*-
"""Milestone 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/samatamerr20/milestone-1.972efa6c-67ef-4b9f-8f07-7badfb3fffcc.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251024/auto/storage/goog4_request%26X-Goog-Date%3D20251024T095400Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D5c62093553d20b7967d5b3bc17399ada56ccfdd00688d7135ebda39c86b60a863dcffbbc45764c789e2a7987ff254200a8e79d29a6f2fbf24b540cb7b25324f9b516a42e89c56e1a1bb606bbfafa74bc5e35dde83d70afaffd979491e89427fe7454886ed65601910cdf597f05d1b709e3175be35c7864959b8c8029943d9f0d277029e69eb553bd67fd70511f2898466c3ff4ce8231cff18241eb12d707ef27be806a3a841d4b36a246289ee45f0b7261066f0046149d1b6250e9d50a6e4f47d331bcd3cd7cad00beb2d8825ad3d7ecf302e62ffdcc979c66027ea8d84d9955d9063f8a475ba0b4bb5946a9f1378c32b32af32459b4abbad7b45aa1d9df8295
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
joebeachcapital_fantasy_football_path = kagglehub.dataset_download('joebeachcapital/fantasy-football')

print('Data source import complete.')

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks

import shap
from lime import lime_tabular

import joblib
from datetime import datetime

df = pd.read_csv('/kaggle/input/fantasy-football/cleaned_merged_seasons.csv')
df.head()

"""This loads a CSV file into a pandas DataFrame named df and then displays the first five rows of the dataset."""

# Basic information
print("\n1. Dataset Info:")
print(f"   - Total rows: {df.shape[0]:,}")
print(f"   - Total columns: {df.shape[1]}")

print("\n2. Column Names:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2d}. {col}")

# Data types
print("\n3. Data Types:")
print(df.dtypes.value_counts())

# Missing values
print("\n4. Missing Values:")
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({
    'Column': missing.index,
    'Missing_Count': missing.values,
    'Missing_Percentage': missing_pct.values
})
missing_df = missing_df[missing_df['Missing_Count'] > 0].sort_values('Missing_Count', ascending=False)
if len(missing_df) > 0:
    print(missing_df.to_string(index=False))
else:
    print("   No missing values found!")

"""before any analysis or modeling, we must understand:
Data structure: What columns exist and their types
Data quality: Missing values, duplicates, data types
Data size: How much data we have to work with
"""

# Columns to remove
columns_to_remove = [
    'ict_index',
    'kickoff_time',
    'round',
    'selected',
    'transfers_balance',
    'transfers_in',
    'transfers_out'
]

df = df.drop(columns=columns_to_remove)
print(f"\nSuccessfully removed {len(columns_to_remove)} columns")

print(f"REMAINING COLUMNS ({df.shape[1]} total)")
for i, col in enumerate(df.columns, 1):
    print(f"{i:3d}. {col}")

"""Remove columns that are either redundant, cause data leakage, or don't contribute meaningful predictive value

ict_index:
A composite metric combining Influence, Creativity, and Threat into a single score.
Why remove it:
We already have the individual components as separate features

kickoff_time:
The date and time when the match started.
Why remove it: exact timestamp isn't predictive

round:
We already have GW which contains the same information

selected, transfers_balance, transfers_out:
out of scope of our reseach question

Impact on Model:
Before removal: Risk of data leakage and redundant features that could:
Cause overfitting (model memorizes patterns that won't exist in real predictions)

"""

# rows with missing team_x
missing_mask = df['team_x'].isna()


# Group by season, GW, and fixture to find team pairs
for (season, gw, fixture), group in df.groupby(['season_x', 'GW', 'fixture']):
    # Get all teams that have team_x filled in this specific fixture
    known_teams = group[group['team_x'].notna()]['team_x'].unique()

    # Get all opponent team names mentioned in this fixture
    opponents = group[group['opp_team_name'].notna()]['opp_team_name'].unique()

    # All teams involved in this fixture (combination of known teams and opponents)
    all_teams = set(list(known_teams) + list(opponents))

    # If we have exactly 2 teams, we can fill missing values
    if len(all_teams) == 2:
        team1, team2 = list(all_teams)

        # For each row with missing team_x in this fixture
        missing_in_group = group[group['team_x'].isna()]

        for idx in missing_in_group.index:
            opponent_name = df.at[idx, 'opp_team_name']

            # If opponent is team1, then player's team is team2 (and vice versa)
            if pd.notna(opponent_name):
                if opponent_name == team1:
                    df.at[idx, 'team_x'] = team2

                elif opponent_name == team2:
                    df.at[idx, 'team_x'] = team1

"""Some rows have missing team_x values.

Team is a critical feature: A player's team affects their performance.
Missing team data: prevents us from using team-related features
Can't drop all missing rows: Would lose too much data

Solution Strategy:
get missing team from opponent and fixture data:
each fixture has exactly 2 teams playing against each other.
If we know the opponent team, we can get the player's team
Group by (season, gameweek, fixture) to find team pairs

If fixture has teams A and B:
If player's opponent is A → player's team is B
If player's opponent is B → player's team is A

Validation: Show examples of filled values to verify correctness

"""

# Count null values
null_count = df.isnull().sum().sum()
print(f"\nTotal null/NaN cells: {null_count}")

"""To make sure I filled all team_x values and there is no missing value."""

df.head()

"""to make sure the team is correct"""

# Exact duplicates
print("EXACT DUPLICATES (all columns):")
exact_dup_mask = df.duplicated(keep=False)
exact_dup_count = exact_dup_mask.sum()

if exact_dup_count > 0:
    print("\n   Example of exact duplicates:")
    print(df[exact_dup_mask].head(10)[['name', 'season_x', 'GW', 'team_x', 'fixture', 'minutes', 'total_points']])

# Partial duplicates
partial_dup_mask = df.duplicated(subset=['name', 'season_x', 'GW'], keep=False)
partial_dup_count = partial_dup_mask.sum()

print(f"Total rows: {len(df):,}")
print(f"Exact duplicates: {exact_dup_count:,}")
print(f"Partial duplicates: {partial_dup_count:,}")

df = df.drop_duplicates()  # removes exact duplicates
df = df.drop_duplicates(subset=['name', 'season_x', 'GW'], keep='first')  # removes partial duplicates

print(f"\nAfter removing duplicates: {df.shape}")

"""Checking for Duplicate Rows

Why Check for Duplicates?
Duplicates can severely bias machine learning models:
Inflated performance: Same data point counted multiple times
Data leakage: Same instance in both train and test sets
Overfitting: Model memorizes duplicates instead of learning patterns

Two Types of Duplicates:
Exact Duplicates (all columns identical)
Partial Duplicates (same player, season, gameweek)

Each player should have one row per gameweek
Multiple rows for same player/gameweek indicates data quality issues
Must resolve before modeling to ensure clean training data

"""

#position of player
#Ensure positions are: GK, DEF, MID, FWD

# Check current positions
print("\nCurrent position values:")
position_counts = df['position'].value_counts()
print(position_counts)

# Create mapping
position_mapping = {
    'GK': 'GK',
    'GKP': 'GK',
    'DEF': 'DEF',
    'MID': 'MID',
    'FWD': 'FWD'
}

# Apply mapping
df['position'] = df['position'].map(position_mapping)

# Check for any unmapped values
unmapped = df[df['position'].isna()]
if len(unmapped) > 0:
    print(f"{len(unmapped)} rows with unmapped positions!")
    print("\nUnmapped position values:")
    print(unmapped['position'].value_counts())
else:
    print("All positions mapped successfully")

print("AFTER UPDATE - Position counts:")
position_counts_after = df['position'].value_counts()
print(position_counts_after)

print(f"Unique positions: {df['position'].unique()}")
print(f"Total rows: {len(df):,}")

"""Position column has inconsistent values (GK, GKP for goalkeepers).

Inconsistency reduces model's ability to learn position-based patterns
Standard categories make analysis clearer

Standardization Mapping:
GK, GKP → GK (Goalkeeper)
DEF → DEF (Defender)
MID → MID (Midfielder)
FWD → FWD (Forward)

Before: Show position value counts (GK, GKP, DEF, MID, FWD)
After: Show standardized counts (GK, DEF, MID, FWD)

"""

# Remove rows with incorrect types
initial_rows = len(df)

# Define expected data types for each column
expected_types = {
    'season_x': 'object',
    'name': 'object',
    'position': 'object',
    'team_x': 'object',
    'assists': 'numeric',
    'bonus': 'numeric',
    'bps': 'numeric',
    'clean_sheets': 'numeric',
    'creativity': 'numeric',
    'element': 'numeric',
    'fixture': 'numeric',
    'goals_conceded': 'numeric',
    'goals_scored': 'numeric',
    'ict_index': 'numeric',
    'influence': 'numeric',
    'kickoff_time': 'object',
    'minutes': 'numeric',
    'opponent_team': 'numeric',
    'opp_team_name': 'object',
    'own_goals': 'numeric',
    'penalties_missed': 'numeric',
    'penalties_saved': 'numeric',
    'red_cards': 'numeric',
    'round': 'numeric',
    'saves': 'numeric',
    'selected': 'numeric',
    'team_a_score': 'numeric',
    'team_h_score': 'numeric',
    'threat': 'numeric',
    'total_points': 'numeric',
    'transfers_balance': 'numeric',
    'transfers_in': 'numeric',
    'transfers_out': 'numeric',
    'value': 'numeric',
    'was_home': 'bool',
    'yellow_cards': 'numeric',
    'GW': 'numeric',
    'form': 'numeric'
}

# Track rows to remove
rows_to_remove = pd.Series([False] * len(df))
issues_found = []


print("CHECKING EACH COLUMN FOR TYPE MISMATCHES:")
print("=" * 80)

for col in df.columns:
    if col not in expected_types:
        print(f"\n Column '{col}' not in expected types - skipping")
        continue

    expected = expected_types[col]

    if expected == 'numeric':
        # Check for non-numeric values
        numeric_check = pd.to_numeric(df[col], errors='coerce')
        invalid_mask = numeric_check.isna() & df[col].notna()
        invalid_count = invalid_mask.sum()

        if invalid_count > 0:
            print(f"\n✗ {col}: {invalid_count} rows with non-numeric values")
            # Show examples
            examples = df[invalid_mask][col].head(5).tolist()
            print(f"   Examples: {examples}")
            rows_to_remove |= invalid_mask
            issues_found.append((col, invalid_count, 'non-numeric'))
        else:
            print(f"✓ {col}: All values are numeric")

    elif expected == 'object':
        # Check that values are strings or null
        non_string_mask = ~df[col].apply(lambda x: isinstance(x, (str, type(None), np.str_)))
        invalid_count = non_string_mask.sum()

        if invalid_count > 0:
            print(f"\n✗ {col}: {invalid_count} rows with non-string values")
            # Show examples
            examples = df[non_string_mask][col].head(5).tolist()
            print(f"   Examples: {examples}")
            rows_to_remove |= non_string_mask
            issues_found.append((col, invalid_count, 'non-string'))
        else:
            print(f"✓ {col}: All values are strings or null")

    elif expected == 'bool':
        # Check that values are boolean
        non_bool_mask = ~df[col].apply(lambda x: isinstance(x, (bool, np.bool_)))
        invalid_count = non_bool_mask.sum()

        if invalid_count > 0:
            print(f"\n✗ {col}: {invalid_count} rows with non-boolean values")
            # Show examples
            examples = df[non_bool_mask][col].head(5).tolist()
            print(f"   Examples: {examples}")
            rows_to_remove |= non_bool_mask
            issues_found.append((col, invalid_count, 'non-boolean'))
        else:
            print(f"✓ {col}: All values are boolean")

# Summary
print("\n" + "=" * 80)
print("SUMMARY:")

if len(issues_found) > 0:
    print(f"\nFound issues in {len(issues_found)} columns:")
    for col, count, issue_type in issues_found:
        print(f"  - {col}: {count} rows with {issue_type} values")

    total_rows_to_remove = rows_to_remove.sum()
    print(f"\nTotal unique rows to remove: {total_rows_to_remove:,}")

    if total_rows_to_remove > 0:
        # Remove rows
        df = df[~rows_to_remove].copy()
        df = df.reset_index(drop=True)

        final_rows = len(df)
        removed = initial_rows - final_rows

        print(f"Rows removed: {removed:,}")
        print(f"Final row count: {final_rows:,}")
    else:
        print("\nNo rows to remove!")
else:
    print("✓ No data type issues found!")

"""Incorrect data types cause model failures:
Numeric columns with strings: Can't calculate statistics or train models
Boolean columns with numbers: Logical operations fail
Mixed types: Unpredictable behavior

Remove rows with incorrect types because:
 Can't reliably convert incorrect values
 Incorrect types indicate data quality issues
 Better to lose a few rows than corrupt the entire dataset
"""

# Calculate Form
# Form = Average of previous 4 gameweeks' total_points / 10

PLAYER_TO_ANALYZE = "Mohamed Salah"  # Change this to any player name

name_cols = [col for col in df.columns if 'name' in col.lower()]
gw_cols = [col for col in df.columns if any(x in col.lower() for x in ['round', 'gw', 'gameweek'])]
points_cols = [col for col in df.columns if 'total_points' in col.lower() or col.lower() == 'points']

if not name_cols:
    raise ValueError("Could not find player name column")
if not gw_cols:
    raise ValueError("Could not find gameweek/round column")
if not points_cols:
    raise ValueError("Could not find total_points column")

name_col = name_cols[0]
gw_col = gw_cols[0]
points_col = points_cols[0]

# Sort data by player, season, and gameweek
df = df.sort_values([name_col, 'season_x', gw_col]).reset_index(drop=True)

# Calculate rolling average of previous 4 gameweeks (grouped by player AND season)
df['form'] = df.groupby([name_col, 'season_x'])[points_col].transform(
    lambda x: x.rolling(window=4, min_periods=1).mean().shift(1)
) / 10

# For the first gameweek of each player, form should be NaN or 0
# We'll set it to 0 for consistency
df['form'] = df['form'].fillna(0)

sample_player = PLAYER_TO_ANALYZE
if sample_player not in df[name_col].values:
    print(f"\n   WARNING: Player '{sample_player}' not found in dataset!")
    sample_player = df.groupby(name_col).size().sort_values(ascending=False).index[0]
    print(f"   Using most common player instead: '{sample_player}'")
else:
    print(f"\n   Analyzing selected player: '{sample_player}'")

verify_data = df[df[name_col] == sample_player].copy()
for idx, row in verify_data.iterrows():
    player_name = row[name_col]
    season = row['season_x']
    gw = int(row[gw_col])
    points = row[points_col]
    form = row['form']

    # Format: "Player Name  Season  GW  Points  Form"
    print(f"{player_name:<20} {season:<10} {gw:>3}  {points:>12.0f}  {form:.6f}")

# Check for any issues
zero_form_count = (df['form'] == 0).sum()
print(f"\n   Rows with form = 0: {zero_form_count:,} (expected for early gameweeks)")


sns.set_style("whitegrid")

# Get player data
player_data = df[df[name_col] == sample_player]

# Get unique seasons
seasons = sorted(player_data['season_x'].unique())
num_seasons = len(seasons)

# Create subplots - 2x2 grid for up to 4 seasons,
if num_seasons <= 4:
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    axes = axes.flatten()
else:
    # If more than 4 seasons, create more subplots
    rows = (num_seasons + 1) // 2
    fig, axes = plt.subplots(rows, 2, figsize=(15, 5 * rows))
    axes = axes.flatten()

# Define colors for each season
colors = ['steelblue', 'darkgreen', 'darkorange', 'crimson', 'purple', 'brown', 'pink', 'gray']

# Plot each season
for i, season in enumerate(seasons):
    season_data = player_data[player_data['season_x'] == season]

    axes[i].plot(season_data[gw_col], season_data['form'], marker='o',
                 linewidth=2, markersize=6, color=colors[i % len(colors)])
    axes[i].fill_between(season_data[gw_col], season_data['form'],
                         alpha=0.3, color=colors[i % len(colors)])
    axes[i].set_xlabel('Gameweek', fontsize=11)
    axes[i].set_ylabel('Form', fontsize=11)
    axes[i].set_title(f'{sample_player} - {season}', fontsize=12, fontweight='bold')
    axes[i].grid(True, alpha=0.3)

# Hide any unused subplots
for i in range(len(seasons), len(axes)):
    axes[i].axis('off')

plt.suptitle(f'Form Evolution: {sample_player} (by Season)', fontsize=14, fontweight='bold', y=0.995)
plt.tight_layout()
plt.show()

# Print new columns
print("\n2. Column Names:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2d}. {col}")

"""Calculating Form

Form = Average of previous 4 gameweeks total_points ÷ 10

Recent performance predicts future performance:
A player "in form" (scoring well recently) is likely to continue
A player "out of form" (scoring poorly) is likely to struggle

Why Previous 4 Gameweeks?
Balance between recency and stability:
 Too few games (1-2): Too volatile, one bad game skews the metric
 Too many games (8+): Too slow to react to form changes
4 games: Industry standard in fantasy football, captures recent trend

Why Divide by 10?
Normalization for model training:
 Raw points range from 0-20+ per gameweek
 Form ranges from 0-2 (more manageable scale)
 Helps neural networks train more efficiently


Calculate per player, per season
Use previous 4 gameweeks
Shift by 1 to avoid data leakage (don't include current gameweek)
Allow calculation even with fewer than 4 games (early season)


Visualization:
Plot form evolution for a sample player across a season( 1 for each season)
Should show smooth trends (not erratic jumps)
Should be 0 or low for first few gameweeks (not enough history)


Why This Feature is Powerful:
Captures momentum: Hot streaks and cold streaks
Time-aware: Recent games matter more than old games

"""

#Position Analysis
#Analyzes which player positions score the most points on average

# Detect points column
points_col = None
for col in ['total_points', 'points', 'total_pts', 'pts', 'points_per_game']:
    if col in df.columns:
        points_col = col
        break

# Detect position column
position_col = None
for col in ['position', 'pos', 'player_position', 'Position', 'element_type',
            'position_id', 'singular_name', 'singular_name_short', 'type']:
    if col in df.columns:
        position_col = col
        break

if not points_col or not position_col:
    raise KeyError(f"Required columns not found. Available columns: {df.columns.tolist()}")

print(f"\nUsing columns: {points_col} (points), {position_col} (position)")

# If position is numeric (1=GK, 2=DEF, 3=MID, 4=FWD), map to names
if df[position_col].dtype in ['int64', 'int32', 'float64']:
    position_mapping = {1: 'Goalkeeper', 2: 'Defender', 3: 'Midfielder', 4: 'Forward'}
    df['position_name'] = df[position_col].map(position_mapping)
    position_col = 'position_name'
    print("Mapped numeric positions to names")

# Calculate average total points by position across all seasons
position_performance = df.groupby(position_col).agg({
    points_col: ['sum', 'mean', 'count']
}).round(2)

position_performance.columns = ['Total_Points_Sum', 'Average_Points', 'Player_Count']
position_performance = position_performance.sort_values('Average_Points', ascending=False)

print("\n" + "="*60)
print("POSITION PERFORMANCE ANALYSIS")
print("="*60)
print(position_performance)
print("="*60)

best_position = position_performance.index[0]
best_avg_points = position_performance['Average_Points'].iloc[0]
print(f"\nBest Position: {best_position} with {best_avg_points:.2f} average points")

# Visualization
fig, ax = plt.subplots(figsize=(12, 7))

colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']
bars = ax.bar(position_performance.index, position_performance['Average_Points'],
              color=colors[:len(position_performance)], edgecolor='black', alpha=0.85, linewidth=1.5)

ax.set_xlabel('Player Position', fontsize=14, fontweight='bold')
ax.set_ylabel('Average Total Points', fontsize=14, fontweight='bold')
ax.set_title('Average Total Points by Player Position Across All Seasons',
             fontsize=16, fontweight='bold', pad=20)
ax.grid(axis='y', alpha=0.3, linestyle='--')

# Add value labels on top of bars
for i, (bar, v) in enumerate(zip(bars, position_performance['Average_Points'])):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
            f'{v:.2f}',
            ha='center', va='bottom', fontweight='bold', fontsize=12)

plt.tight_layout()
plt.show()

print("REASONING")
print(f"   - {best_position}s typically have more opportunities to score points through:")
print("     • Goals and assists (high point values)")
print("     • Bonus points for match performance")
print("     • Consistent playing time")
print("   - Defenders and Goalkeepers rely more on clean sheets, which are less frequent")

"""Which Positions Score Most

Why This Matters:
If forwards score more on average, prioritize forwards in team selection
If defenders score less, budget allocation should reflect this
Understanding position value informs transfer decisions

Analysis Approach:
Group by position: Calculate total and average points per position
Visualize: Bar chart showing average points by position
Interpret: Explain why certain positions score more

Statistics Table:
Total points sum per position
Average points per position
Number of players per position

Position is a key feature: Model will learn position-based scoring patterns
"""

#How did the top 5 players' form evolve across gameweek, Are top players in form the same as top players with highest total points?

player_id_col = None
for col in ['element', 'player_id', 'id', 'Element']:
    if col in df.columns:
        player_id_col = col
        break

# Try to find player name column
player_name_col = None
for col in ['name', 'player_name', 'player', 'full_name', 'web_name', 'first_name', 'last_name']:
    if col in df.columns:
        player_name_col = col
        break

gameweek_col = None
for col in ['gameweek', 'GW', 'round', 'week', 'game_week', 'event']:
    if col in df.columns:
        gameweek_col = col
        break

points_col = None
for col in ['total_points', 'points', 'total_pts', 'pts']:
    if col in df.columns:
        points_col = col
        break

season_col = None
for col in ['season', 'Season', 'year', 'Year', 'season_name', 'season_x']:
    if col in df.columns:
        season_col = col
        break

if not all([player_id_col, gameweek_col, points_col]):
    raise KeyError("Required columns not found")

if 'form' not in df.columns:
    raise KeyError("'form' column not found. Run Cell 6 first.")

if player_name_col:
    player_names = df.groupby(player_id_col)[player_name_col].first().to_dict()
else:
    # If no name column, use Player ID as display name
    player_names = {pid: f"Player {pid}" for pid in df[player_id_col].unique()}


# Filter for 2022-23 season if season column exists
if season_col:
    season_2022_23 = df[df[season_col] == '2022-23'].copy()
    if len(season_2022_23) == 0:
        # Try alternative season formats
        season_2022_23 = df[df[season_col].astype(str).str.contains('2022|22-23|2022-23', na=False)].copy()
    if len(season_2022_23) == 0:
        season_2022_23 = df.copy()
    else:
        print(f"Found {len(season_2022_23)} records for 2022-23 season")
else:
    season_2022_23 = df.copy()

# Identify top 5 players by total points
top_players_by_points = season_2022_23.groupby(player_id_col)[points_col].sum().nlargest(5)
print("\n1. Top 5 Players by Total Points (2022-23):")
for i, (player_id, points) in enumerate(top_players_by_points.items(), 1):
    player_name = player_names.get(player_id, f"Player {player_id}")
    print(f"   {i}. {player_name}: {points:.0f} points")

# Identify top 5 players by average form
top_players_by_form = season_2022_23.groupby(player_id_col)['form'].mean().nlargest(5)
print("\n2. Top 5 Players by Average Form (2022-23):")
for i, (player_id, form) in enumerate(top_players_by_form.items(), 1):
    player_name = player_names.get(player_id, f"Player {player_id}")
    print(f"   {i}. {player_name}: {form:.2f} form")

# Check overlap
overlap = set(top_players_by_points.index) & set(top_players_by_form.index)
print(f"\n3. Players in Both Top 5 Lists: {len(overlap)} out of 5")
if overlap:
    overlap_names = [player_names.get(pid, f"Player {pid}") for pid in overlap]
    print(f"   - Players: {', '.join(overlap_names)}")

# Visualize form evolution for top 5 by points
fig, axes = plt.subplots(2, 1, figsize=(16, 12))

# Plot 1: Form Evolution
for player_id in top_players_by_points.index:
    player_data = season_2022_23[season_2022_23[player_id_col] == player_id].sort_values(gameweek_col)
    player_name = player_names.get(player_id, f"Player {player_id}")
    axes[0].plot(player_data[gameweek_col], player_data['form'], marker='o',
                 label=player_name, linewidth=2, markersize=4)

axes[0].set_xlabel('Gameweek', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Form', fontsize=12, fontweight='bold')
axes[0].set_title('Form Evolution of Top 5 Players (by Total Points) - 2022-23 Season',
                  fontsize=14, fontweight='bold')
axes[0].legend(loc='best', fontsize=10)
axes[0].grid(True, alpha=0.3)

# Plot 2: Total Points per Gameweek
for player_id in top_players_by_points.index:
    player_data = season_2022_23[season_2022_23[player_id_col] == player_id].sort_values(gameweek_col)
    player_name = player_names.get(player_id, f"Player {player_id}")
    axes[1].plot(player_data[gameweek_col], player_data[points_col], marker='s',
                 label=player_name, linewidth=2, markersize=4, alpha=0.7)

axes[1].set_xlabel('Gameweek', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Total Points', fontsize=12, fontweight='bold')
axes[1].set_title('Total Points per Gameweek - Top 5 Players (2022-23 Season)',
                  fontsize=14, fontweight='bold')
axes[1].legend(loc='best', fontsize=10)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Comparison visualization
fig, ax = plt.subplots(figsize=(14, 8))

# Create comparison data
comparison_data = pd.DataFrame({
    'Player_ID': list(top_players_by_points.index),
    'Player_Name': [player_names.get(pid, f"Player {pid}") for pid in top_players_by_points.index],
    'Total_Points': top_players_by_points.values,
    'Avg_Form': [season_2022_23[season_2022_23[player_id_col] == p]['form'].mean()
                 for p in top_players_by_points.index]
})

x = np.arange(len(comparison_data))
width = 0.35

bars1 = ax.bar(x - width/2, comparison_data['Total_Points'], width,
               label='Total Points', color='#2ca02c', alpha=0.8, edgecolor='black')
ax2 = ax.twinx()
bars2 = ax2.bar(x + width/2, comparison_data['Avg_Form'], width,
                label='Average Form', color='#ff7f0e', alpha=0.8, edgecolor='black')

ax.set_xlabel('Player', fontsize=12, fontweight='bold')
ax.set_ylabel('Total Points', fontsize=12, fontweight='bold', color='#2ca02c')
ax2.set_ylabel('Average Form', fontsize=12, fontweight='bold', color='#ff7f0e')
ax.set_title('Top 5 Players: Total Points vs Average Form (2022-23)',
             fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(comparison_data['Player_Name'], rotation=45, ha='right')
ax.tick_params(axis='y', labelcolor='#2ca02c')
ax2.tick_params(axis='y', labelcolor='#ff7f0e')

# Add legends
lines1, labels1 = ax.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax.legend(lines1 + lines2, labels1 + labels2, loc='upper left')

plt.tight_layout()
plt.show()

print("\n Analysis:")
if len(overlap) == 5:
    print("The top 5 players by form are EXACTLY the same as top 5 by total points")
elif len(overlap) >= 3:
    print(f"There is significant overlap ({len(overlap)}/5 players)")
    print("Form is a good indicator of overall performance")
else:
    print(f"Limited overlap ({len(overlap)}/5 players)")
    print("Form and total points measure different aspects of performance")
    print("Total points = cumulative season performance")
    print("Form = recent 4-week performance trend")

print(f"\n{'='*80}")

"""How did the top 5 players' form evolve across the season?
Are top players by form the same as top players by total points?

Stable form = more predictable future performance

Form vs Total Points
Form = Recent performance (last 4 gameweeks)
Total Points = Cumulative season performance


Visualize Form Evolution:
Line plot: Form over gameweeks for top 5 players
Shows trends, peaks, and troughs
Reveals consistency patterns

Compare Lists:
Calculate overlap between top 5 by points and top 5 by form
Interpret what overlap means

Expected Findings:
Scenario A: High Overlap (4-5 players in both lists)
Interpretation: Top performers maintain consistent form
Implication: Form is a reliable predictor of total points

Scenario B: Low Overlap (0-2 players in both lists)
Interpretation: Recent form ≠ season-long performance
Implication: Some players have hot streaks, others are consistently good


Visualizations:

Plot 1: Form Evolution (Line Chart)
X-axis: Gameweek
Y-axis: Form
5 lines (one per top player)
 What to look for:
  - Smooth lines = consistent performers
  - Spiky lines = volatile performers

Plot 2: Total Points per Gameweek (Line Chart)
Shows actual points scored each week
Compare to form (which is lagged average)
 What to look for:
  - Correlation between form and subsequent points
  - Big point hauls followed by form increases

Plot 3: Comparison Bar Chart
- Dual y-axis: Total points (left) vs Average form (right)
- Shows both metrics side-by-side for top 5 players


Why This Analysis is Critical:

Validates that form is a useful feature

If form predicts points well, model should weight it heavily
If not, model needs to learn more complex patterns

High overlap = trust form when selecting players
Low overlap = consider both recent and long-term performance
"""

# all the above is correct

print("\n" + "="*80)
print("STEP 1: Creating upcoming_total_points (shifted one week ahead)")
print("="*80)

# Detect column names
name_col = None
gw_col = None
points_col = None

for col in df.columns:
    col_lower = col.lower()
    if 'name' in col_lower and name_col is None:
        name_col = col
    if any(x in col_lower for x in ['gw', 'round', 'gameweek']) and gw_col is None:
        gw_col = col
    if 'total_points' in col_lower and points_col is None:
        points_col = col

print(f"\nDetected columns:")
print(f"  - Player name: {name_col}")
print(f"  - Gameweek: {gw_col}")
print(f"  - Total points: {points_col}")

# Sort by player and gameweek
df = df.sort_values([name_col, gw_col]).reset_index(drop=True)

# Create upcoming_total_points by shifting total_points by -1 within each player group
df['upcoming_total_points'] = df.groupby(name_col)[points_col].shift(-1)

# Count how many rows have valid upcoming_total_points
valid_rows = df['upcoming_total_points'].notna().sum()
dropped_rows = df['upcoming_total_points'].isna().sum()

print(f"\n✓ Created upcoming_total_points column")
print(f"  - Valid rows: {valid_rows}")
print(f"  - Rows to drop (last week for each player): {dropped_rows}")

# Drop rows where upcoming_total_points is NaN (last gameweek for each player)
df = df.dropna(subset=['upcoming_total_points']).reset_index(drop=True)
print(f"  - Final dataset size: {df.shape[0]} rows")

# Show example for one player
sample_player = df[name_col].value_counts().index[1200]
sample_data = df[df[name_col] == sample_player][[name_col, gw_col, points_col, 'upcoming_total_points']].head(10)
print(f"\nExample for {sample_player} (first 10 gameweeks):")
print(sample_data.to_string(index=False))

"""## Step 9: Creating the Target Variable - upcoming_total_points

### What Are We Predicting?
**Target:** `upcoming_total_points` = Points scored in the NEXT gameweek

### Why This Target?
**Fantasy football is about predicting future performance:**
- We have data up to gameweek N
- We want to predict points in gameweek N+1
- This is exactly what fantasy managers need for team selection

### Implementation:
\`\`\`python
df['upcoming_total_points'] = df.groupby('name')['total_points'].shift(-1)
\`\`\`

**What `shift(-1)` does:**
- Takes the `total_points` column
- Shifts it up by 1 row (within each player group)
- Result: Each row now has the NEXT gameweek's points

### Example:
\`\`\`
Player: Mohamed Salah
GW  total_points  upcoming_total_points
1   12            8                    ← GW2's points
2   8             15                   ← GW3's points
3   15            6                    ← GW4's points
4   6             NaN                  ← No GW5 data yet
\`\`\`

### Why Drop Rows with NaN upcoming_total_points?
**Last gameweek for each player has no "next" gameweek:**
- Can't predict what we don't have data for
- These rows are useless for training
- Dropping them prevents model errors

### Data Leakage Prevention:
**Critical:** We use features from gameweek N to predict gameweek N+1
- **Correct:** Use GW4 stats (goals, assists, form) to predict GW5 points
- **WRONG:** Use GW5 stats to predict GW5 points (cheating!)

**Our approach prevents leakage:**
- `shift(-1)` ensures target is always from the FUTURE
- Form calculation uses `shift(1)` to only use PAST data
- Train/test split will be time-based (train on early GWs, test on late GWs)

### Evidence:
**Show example for one player:**
- Display 10 consecutive gameweeks
- Show total_points and upcoming_total_points side-by-side
- Verify upcoming_total_points = next row's total_points

**Dataset size change:**
- Before: X rows
- After: Y rows (X - number of players, since we drop last GW for each)

---

"""

#==============================================================================
# CELL 2: OPTIMIZED FEATURE ENGINEERING (4 GW LOOKBACK)
#==============================================================================
print("\n" + "="*80)
print("STEP 1: OPTIMIZED FEATURE ENGINEERING")
print("="*80)

# Sort data
df = df.sort_values(['name', 'GW']).reset_index(drop=True)

print("\n🎯 Optimization Strategy:")
print("  • BOOST form importance (don't divide by 10)")
print("  • ADD explicit goals/assists features")
print("  • REMOVE redundant features (value, bps, goal_involvement)")
print("  • KEEP ICT components (creativity, influence, threat)")
print("  • USE CONSISTENT 4 GW lookback for all features")
print("")

# ============================================================================
# 1. Weighted Form (BOOSTED - not divided by 10)
# ============================================================================
def calculate_weighted_form(series):
    """Recent games matter more: weights [0.1, 0.2, 0.3, 0.4]"""
    return series.rolling(4, min_periods=1).apply(
        lambda x: np.average(x, weights=[0.1, 0.2, 0.3, 0.4][-len(x):]) if len(x) > 0 else 0
    ).shift(1)
    # NOTE: NOT dividing by 10 anymore - keeps full magnitude

df['weighted_form'] = df.groupby('name')['total_points'].transform(
    calculate_weighted_form
).fillna(0)
print("✓ 1. weighted_form (BOOSTED - full magnitude) - Recent performance")

# ============================================================================
# 2. Goals Last 4 (EXPLICIT - separate from assists)
# ============================================================================
df['goals_last_4'] = df.groupby('name')['goals_scored'].transform(
    lambda x: x.rolling(4, min_periods=1).sum().shift(1)
).fillna(0)
print("✓ 2. goals_last_4 (NEW) - Direct goal-scoring output")

# ============================================================================
# 3. Assists Last 4 (EXPLICIT - separate from goals)
# ============================================================================
df['assists_last_4'] = df.groupby('name')['assists'].transform(
    lambda x: x.rolling(4, min_periods=1).sum().shift(1)
).fillna(0)
print("✓ 3. assists_last_4 (NEW) - Direct playmaking output")

# ============================================================================
# 4. Minutes Average Last 4 (UPDATED from 6 to 4)
# ============================================================================
df['minutes_avg_last_4'] = df.groupby('name')['minutes'].transform(
    lambda x: x.rolling(4, min_periods=1).mean().shift(1)
).fillna(0)
print("✓ 4. minutes_avg_last_4 - Playing time consistency")

# ============================================================================
# 5. Minutes Stability Last 4 (UPDATED from 6 to 4)
# ============================================================================
df['minutes_std_last_4'] = df.groupby('name')['minutes'].transform(
    lambda x: x.rolling(4, min_periods=2).std().shift(1)
).fillna(0)

# Convert to stability: low std = high stability
df['minutes_stability'] = 1 / (df['minutes_std_last_4'] + 1)
print("✓ 5. minutes_stability - Rotation risk indicator")

# ============================================================================
# 6. Clean Sheet Rate Last 4 (UPDATED from 6 to 4)
# ============================================================================
df['cs_rate_last_4'] = df.groupby('name')['clean_sheets'].transform(
    lambda x: x.rolling(4, min_periods=1).mean().shift(1)
).fillna(0)
print("✓ 6. cs_rate_last_4 - Defensive reliability")

print("\n✅ Created 6 optimized features (ALL using 4 GW lookback)")
print("   • Removed: value, bps, goal_involvement_last_4, saves_per_90_gk")
print("   • Added: goals_last_4, assists_last_4 (explicit attack signals)")
print("   • Boosted: weighted_form (10x stronger)")
print("   • Consistency: ALL features use past 4 GWs")

#==============================================================================
# CELL 3: DEFINE OPTIMIZED FEATURE SET
#==============================================================================
print("\n" + "="*80)
print("STEP 2: OPTIMIZED FEATURE SELECTION")
print("="*80)

# Base features from dataset (3)
base_features = [
    'creativity',    # FPL metric - chance creation
    'influence',     # FPL metric - game impact
    'threat',        # FPL metric - attacking threat
]

# Engineered features (6)
engineered_features = [
    'weighted_form',        # Recent performance (BOOSTED)
    'goals_last_4',         # Direct attacking (NEW)
    'assists_last_4',       # Direct playmaking (NEW)
    'minutes_avg_last_4',   # Availability (UPDATED from 6 to 4)
    'minutes_stability',    # Rotation risk
    'cs_rate_last_4',       # Defensive value (UPDATED from 6 to 4)
]

# Context features (2)
context_features = [
    'position',      # Role in team
    'was_home',      # Home advantage
]

# Combine all
final_features = base_features + engineered_features + context_features

print(f"\n📋 Optimized Feature Set ({len(final_features)} features):")
print("\n🔹 FPL Underlying Metrics (3):")
for feat in base_features:
    print(f"  • {feat}")

print("\n🔹 Engineered Performance Features (6) - ALL using 4 GW lookback:")
for feat in engineered_features:
    print(f"  • {feat}")

print("\n🔹 Context Features (2):")
for feat in context_features:
    print(f"  • {feat}")

print("\n❌ REMOVED (Redundant/Low Value):")
print("  • value (price dominance)")
print("  • bps (correlated with form)")
print("  • goal_involvement_last_4 (replaced by separate goals/assists)")
print("  • saves_per_90_gk (minimal impact)")
print("  • GW (season progression - minimal predictive value)")

# Verify all features exist
missing = [f for f in final_features if f not in df.columns]
if missing:
    print(f"\n⚠️  Missing: {missing}")
    final_features = [f for f in final_features if f in df.columns]
else:
    print(f"\n✅ All {len(final_features)} features verified in dataset")
    print("   🎯 Consistency: ALL engineered features use 4 GW lookback window")

# ============================================================================
# CELL: FEATURE PREPARATION WITH PROPER TRAIN/VAL/TEST SPLIT
# ============================================================================
print("\n" + "="*80)
print("STEP 3: FEATURE PREPARATION")
print("="*80)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Define target
target = 'upcoming_total_points'

# Define features
base_features = [
    'creativity',
    'influence',
    'threat',
]

engineered_features = [
    'weighted_form',
    'goals_last_4',
    'assists_last_4',
    'minutes_avg_last_4',
    'minutes_stability',
    'cs_rate_last_4',
]

context_features = [
    'position',
    'was_home',
]

all_features = base_features + engineered_features + context_features

print(f"\n📋 Feature Set ({len(all_features)} features):")
print("\n🔹 FPL Underlying Metrics (3):")
for feat in base_features:
    print(f"  • {feat}")

print("\n🔹 Engineered Performance Features (6):")
for feat in engineered_features:
    print(f"  • {feat}")

print("\n🔹 Context Features (2):")
for feat in context_features:
    print(f"  • {feat}")

print("\n🔧 Encoding position...")
le_position = LabelEncoder()
df['position_encoded'] = le_position.fit_transform(df['position'])

# Create mapping for reference
position_mapping = dict(zip(le_position.classes_, le_position.transform(le_position.classes_)))
print(f"   Position encoding: {position_mapping}")

# Replace 'position' with 'position_encoded' in features
all_features_encoded = [f if f != 'position' else 'position_encoded' for f in all_features]

# Prepare feature matrix
X = df[all_features_encoded].copy()
y = df[target].copy()

print(f"\nDataset shape:")
print(f"  - Features (X): {X.shape}")
print(f"  - Target (y): {y.shape}")

# Check for missing values
missing_count = X.isnull().sum().sum()
if missing_count > 0:
    print(f"\n⚠ WARNING: {missing_count} missing values found")
    X = X.fillna(0)
    print(f"   ✓ Filled with 0")
else:
    print(f"\n✓ No missing values in feature matrix")

# IMPROVED: Proper train/val/test split (70/15/15)
print("\n🎯 Creating proper train/val/test split...")
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

print(f"\nTrain-Val-Test split (70-15-15):")
print(f"  - Training set: {X_train.shape[0]} samples")
print(f"  - Validation set: {X_val.shape[0]} samples")
print(f"  - Test set: {X_test.shape[0]} samples")

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

print(f"\n✓ Features scaled using StandardScaler")
print(f"  - Training set: {X_train_scaled.shape}")
print(f"  - Validation set: {X_val_scaled.shape}")
print(f"  - Test set: {X_test_scaled.shape}")

print("\n✓ Data preparation complete!")

#==============================================================================
# CELL 20: AGGRESSIVE FFNN OPTIMIZATION - SIMPLIFIED APPROACH
#==============================================================================
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("="*80)
print("STEP 4: AGGRESSIVE FFNN OPTIMIZATION")
print("="*80)

print("\n🎯 New Strategy:")
print("  • Remove ALL regularization (let model learn freely)")
print("  • Much wider network (128→64→32)")
print("  • MSE loss instead of Huber")
print("  • Higher learning rate")
print("  • More epochs")
print("")

print("Building aggressive neural network...")
print("Architecture: 128 → 64 → 32 → 16 → Output (NO regularization)")

model = keras.Sequential([
    keras.Input(shape=(X_train_scaled.shape[1],)),

    # Very wide first layer
    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.2),

    # Second layer
    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.2),

    # Third layer
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.1),

    # Fourth layer
    layers.Dense(16, activation='relu'),

    # Output
    layers.Dense(1)
])

# Higher learning rate
optimizer = keras.optimizers.Adam(learning_rate=0.002)

model.compile(
    optimizer=optimizer,
    loss='mse',  # Back to MSE
    metrics=['mae']
)

print("\nModel Architecture:")
model.summary()

print("\nSetting up callbacks...")

# Less aggressive early stopping
early_stop = callbacks.EarlyStopping(
    monitor='val_loss',
    patience=30,
    restore_best_weights=True,
    verbose=1
)

# Learning rate reduction
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=10,
    min_lr=0.00001,
    verbose=1
)

print("   ✓ Early stopping (patience=30)")
print("   ✓ Learning rate reduction")

# Train the model
print("\nTraining Neural Network...")
history = model.fit(
    X_train_scaled, y_train,
    epochs=150,  # More epochs
    batch_size=64,  # Bigger batches
    validation_data=(X_val_scaled, y_val),
    verbose=1,
    callbacks=[early_stop, reduce_lr]
)

print(f"\n✓ Training completed in {len(history.history['loss'])} epochs")

# ============================================================================
# EVALUATION
# ============================================================================
print("\n" + "="*80)
print("STEP 5: MODEL EVALUATION")
print("="*80)

# Predict on all sets
y_pred_train = model.predict(X_train_scaled, verbose=0).flatten()
y_pred_val = model.predict(X_val_scaled, verbose=0).flatten()
y_pred_test = model.predict(X_test_scaled, verbose=0).flatten()

# Calculate metrics
train_mae = mean_absolute_error(y_train, y_pred_train)
train_r2 = r2_score(y_train, y_pred_train)

val_mae = mean_absolute_error(y_val, y_pred_val)
val_r2 = r2_score(y_val, y_pred_val)

test_mae = mean_absolute_error(y_test, y_pred_test)
test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)
test_r2 = r2_score(y_test, y_pred_test)

# Display results
print(f"\n{'Set':<12} {'MAE':<8} {'R²':<8}")
print("-" * 30)
print(f"{'Training':<12} {train_mae:<8.3f} {train_r2:<8.3f}")
print(f"{'Validation':<12} {val_mae:<8.3f} {val_r2:<8.3f}")
print(f"{'Test':<12} {test_mae:<8.3f} {test_r2:<8.3f}")

print(f"\nTest Set Detailed Metrics:")
print(f"  - MAE: {test_mae:.3f}")
print(f"  - RMSE: {test_rmse:.3f}")
print(f"  - R² Score: {test_r2:.3f}")

print(f"\nInterpretation:")
print(f"  - On average, predictions are off by {test_mae:.2f} points")
print(f"  - The model explains {test_r2*100:.1f}% of the variance")

if test_r2 > 0.5:
    print(f"  - ✓ Good model performance (R² > 0.5)")
elif test_r2 > 0.3:
    print(f"  - ⚠ Moderate model performance (0.3 < R² < 0.5)")
elif test_r2 > 0.15:
    print(f"  - ⚠ Poor but improving (0.15 < R² < 0.3)")
else:
    print(f"  - ✗ Very poor - fundamental issue with features or data")

print("\n✓ Evaluation complete!")

# ============================================================================
# VISUALIZATIONS
# ============================================================================
print("\nCreating evaluation visualizations...")

# Figure 1: Training Progress
print("\n[1/2] Creating training progress plot...")
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

epochs = range(1, len(history.history['loss']) + 1)

# Loss plot
axes[0].plot(epochs, history.history['loss'], 'b-', label='Training Loss', linewidth=2)
axes[0].plot(epochs, history.history['val_loss'], 'r-', label='Validation Loss', linewidth=2)
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Loss', fontsize=12)
axes[0].set_title('Training and Validation Loss', fontsize=14, fontweight='bold')
axes[0].legend(fontsize=10)
axes[0].grid(True, alpha=0.3)

# MAE plot
axes[1].plot(epochs, history.history['mae'], 'b-', label='Training MAE', linewidth=2)
axes[1].plot(epochs, history.history['val_mae'], 'r-', label='Validation MAE', linewidth=2)
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('MAE (Mean Absolute Error)', fontsize=12)
axes[1].set_title('Training and Validation MAE', fontsize=14, fontweight='bold')
axes[1].legend(fontsize=10)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Figure 2: Performance Metrics
print("\n[2/2] Creating performance metrics plot...")
fig, ax = plt.subplots(figsize=(12, 6))

metrics = ['MAE', 'MSE', 'RMSE', 'R²']
values = [mae, mse, rmse, r2]
colors = ['#3498db', '#9b59b6', '#e74c3c', '#2ecc71']

bars = ax.bar(metrics, values, color=colors, alpha=0.7, edgecolor='black', linewidth=1.5)

# Add value labels
for bar, value in zip(bars, values):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height,
            f'{value:.3f}',
            ha='center', va='bottom', fontsize=12, fontweight='bold')

ax.set_ylabel('Metric Value', fontsize=12)
ax.set_title('Model Performance Metrics', fontsize=14, fontweight='bold')
ax.grid(axis='y', alpha=0.3)

# Add info box
info_text = f'Architecture: 64→32→16\nFeatures: {X_train_scaled.shape[1]}\nEpochs: {len(history.history["loss"])}'
ax.text(0.98, 0.97, info_text, transform=ax.transAxes,
        fontsize=10, verticalalignment='top', horizontalalignment='right',
        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

plt.tight_layout()
plt.show()

print("\n✓ Evaluation complete!")

#==============================================================================
# CELL 22: POSITION-SPECIFIC SHAP ANALYSIS
#==============================================================================
print("="*80)
print("STEP 7: POSITION-SPECIFIC SHAP ANALYSIS")
print("="*80)

# Prepare background dataset
print("\n[1/5] Preparing SHAP explainer...")
background = shap.sample(
    pd.DataFrame(X_train_scaled, columns=all_features_encoded),
    100,
    random_state=42
)
explainer = shap.Explainer(model, background)
print(f"   ✓ Background dataset: {background.shape[0]} samples")
print(f"   ✓ Explainer created")

# Get position column from original test data (before encoding)
X_test_original = df.loc[X_test.index].copy()
X_test_df = pd.DataFrame(X_test_scaled, columns=all_features_encoded, index=X_test.index)

# Calculate SHAP values for entire test set
print("\n[2/5] Calculating SHAP values for test set...")
shap_values = explainer(X_test_df)
print(f"   ✓ SHAP values calculated for {len(X_test_df):,} test samples")

try:
    _ = le.classes_
    print("✓ Found position encoder from model training")
except NameError:
    print("⚠ Position encoder not found, recreating it...")
    from sklearn.preprocessing import LabelEncoder
    le = LabelEncoder()
    le.classes_ = np.array(['DEF', 'FWD', 'GK', 'MID'])  # Standard FPL positions
    print("✓ Position encoder recreated")

# Get position mapping back (decode from encoded values)
position_mapping_reverse = {i: pos for i, pos in enumerate(le.classes_)}

# Add position column to test data for filtering
X_test_with_pos = X_test.copy()
X_test_with_pos['position_name'] = X_test_with_pos['position'].map(position_mapping_reverse)

positions = ['FWD', 'MID', 'DEF', 'GK']
position_shap_results = {}

for pos in positions:
    print(f"\n[3/5] Analyzing position: {pos}")

    # Filter test data for this position
    pos_mask = X_test_with_pos['position_name'] == pos
    X_test_pos = X_test_scaled[pos_mask]

    if len(X_test_pos) == 0:
        print(f"   ⚠ No test samples for {pos}, skipping...")
        continue

    print(f"   - Test samples for {pos}: {len(X_test_pos)}")

    # Calculate SHAP values for this position
    X_test_pos_df = pd.DataFrame(X_test_pos, columns=all_features)
    shap_values_pos = explainer(X_test_pos_df)

    position_shap_results[pos] = shap_values_pos

    print(f"   ✓ SHAP values calculated for {pos}")

print(f"\n✓ Stored SHAP results for {len(position_shap_results)} positions: {list(position_shap_results.keys())}")

print("\n[4/5] Creating position-specific SHAP visualizations...")

for pos in positions:
    if pos not in position_shap_results:
        continue

    print(f"\n{'='*80}")
    print(f"SHAP ANALYSIS: {pos}")
    print(f"{'='*80}")

    shap_values_pos = position_shap_results[pos]

    # Bar plot - feature importance
    print(f"\n[{pos}] Feature Importance (Bar Plot)")
    shap.summary_plot(
        shap_values_pos.values,
        pd.DataFrame(shap_values_pos.data, columns=all_features),
        feature_names=all_features,
        plot_type='bar',
        show=True,
        max_display=10
    )

    # Beeswarm plot - feature effects
    print(f"\n[{pos}] Feature Effects (Beeswarm Plot)")
    shap.summary_plot(
        shap_values_pos.values,
        pd.DataFrame(shap_values_pos.data, columns=all_features),
        feature_names=all_features,
        show=True,
        max_display=10
    )

    # Calculate mean absolute SHAP values
    mean_abs_shap = np.abs(shap_values_pos.values).mean(axis=0)
    feature_importance = pd.DataFrame({
        'Feature': all_features,
        'Mean |SHAP|': mean_abs_shap
    }).sort_values('Mean |SHAP|', ascending=False)

    print(f"\n[{pos}] Top 5 Most Important Features:")
    print(feature_importance.head(5).to_string(index=False))

print("\n[5/5] Position-specific SHAP analysis complete!")

#==============================================================================
# CELL: SHAP LOCAL ANALYSIS (WATERFALL + FORCE PLOTS)
#==============================================================================
print("\n" + "="*80)
print("SHAP LOCAL ANALYSIS - INDIVIDUAL PLAYER EXPLANATIONS")
print("="*80)

print("\nGenerating local explanations (waterfall + force plots) for each position...")

# Initialize SHAP JavaScript for force plots
shap.initjs()

for pos in positions:
    if pos not in position_shap_results:
        continue

    print(f"\n{'='*80}")
    print(f"LOCAL SHAP ANALYSIS: {pos}")
    print(f"{'='*80}")

    shap_values_pos = position_shap_results[pos]

    # Select a random instance from this position
    instance_idx = np.random.randint(0, len(shap_values_pos))

    # Get player info
    pos_mask = X_test_with_pos['position_name'] == pos
    pos_test_indices = X_test_with_pos[pos_mask].index
    player_name = df.loc[pos_test_indices[instance_idx], 'name'] if 'name' in df.columns else f"{pos} Player"

    # Get prediction details
    base_value = shap_values_pos[instance_idx].base_values
    if hasattr(base_value, '__len__'):
        base_value = base_value[0]

    shap_contribution = shap_values_pos[instance_idx].values.sum()
    final_prediction = base_value + shap_contribution

    print(f"\nPlayer: {player_name}")
    print(f"   Base value (average prediction): {base_value:.2f}")
    print(f"   SHAP contribution: {shap_contribution:+.2f}")
    print(f"   Final prediction: {final_prediction:.2f}")

    # Waterfall plot
    print(f"\n[{pos}] Waterfall Plot - Feature Contributions")
    plt.figure(figsize=(10, 6))
    shap.plots.waterfall(shap_values_pos[instance_idx], show=False)
    plt.title(f'SHAP Waterfall Plot - {pos} Player\n{player_name}',
              fontsize=14, fontweight='bold', pad=20)
    plt.tight_layout()
    plt.show()

    # Force plot
    print(f"\n[{pos}] Force Plot - Visual Feature Impact")
    shap.plots.force(shap_values_pos[instance_idx], matplotlib=True, show=False)
    plt.title(f'SHAP Force Plot - {pos} Player\n{player_name}',
              fontsize=14, fontweight='bold', pad=20)
    plt.tight_layout()
    plt.show()

    # Show top contributing features
    feature_impacts = list(zip(all_features, shap_values_pos[instance_idx].values))
    feature_impacts.sort(key=lambda x: abs(x[1]), reverse=True)

    print(f"\n[{pos}] Top 5 Feature Contributions:")
    print(f"{'Feature':<25} {'SHAP Value':>15} {'Impact':>10}")
    print("-" * 50)
    for feat, val in feature_impacts[:5]:
        impact = "↑ Higher" if val > 0 else "↓ Lower"
        print(f"{feat:<25} {val:>15.4f} {impact:>10}")

print("\n✓ SHAP local analysis complete!")

#==============================================================================
# CELL: POSITION-SPECIFIC LIME ANALYSIS
#==============================================================================
from lime import lime_tabular

print("\n" + "="*80)
print("POSITION-SPECIFIC LIME ANALYSIS")
print("="*80)

print("\n[1/3] Setting up LIME explainer...")
explainer_lime = lime_tabular.LimeTabularExplainer(
    X_train_scaled,
    feature_names=all_features,
    mode='regression',  # Regression mode for predicting continuous points
    discretize_continuous=True,
    random_state=42
)

def predict_fn(X):
    """Prediction function for LIME - returns raw predictions"""
    return model.predict(X, verbose=0).flatten()

print("   ✓ LIME explainer created (regression mode)")

print("\n[2/3] Generating LIME explanations for each position...")

for pos in positions:
    print(f"\n{'='*80}")
    print(f"LIME ANALYSIS: {pos}")
    print(f"{'='*80}")

    # Filter test data for this position
    pos_mask = X_test_with_pos['position_name'] == pos
    pos_indices = X_test_with_pos[pos_mask].index

    if len(pos_indices) == 0:
        print(f"   ⚠ No test samples for {pos}, skipping...")
        continue

    # Get a random sample from this position
    sample_idx = np.random.choice(pos_indices)

    # Get the index in X_test_scaled
    test_idx = X_test.index.get_loc(sample_idx)

    instance = X_test_scaled[test_idx]
    predicted_value = predict_fn(instance.reshape(1, -1))[0]

    print(f"\nExplaining {pos} player (test index {test_idx}):")
    print(f"   Predicted points: {predicted_value:.2f}")

    # Generate LIME explanation
    exp = explainer_lime.explain_instance(
        instance,
        predict_fn,
        num_features=10
    )

    # Get feature contributions
    feature_contributions = exp.as_list()

    # Split into positive and negative contributions
    positive_features = [(f, c) for f, c in feature_contributions if c > 0]
    negative_features = [(f, c) for f, c in feature_contributions if c < 0]

    # Sort by absolute contribution
    positive_features.sort(key=lambda x: abs(x[1]), reverse=True)
    negative_features.sort(key=lambda x: abs(x[1]), reverse=True)

    fig = plt.figure(figsize=(14, 10))
    gs = fig.add_gridspec(3, 1, height_ratios=[1, 4, 2], hspace=0.3)

    # Top: Prediction value only (no actual value)
    ax_pred = fig.add_subplot(gs[0])
    ax_pred.axis('off')
    ax_pred.text(0.5, 0.5, f'Predicted Points: {predicted_value:.2f}',
                 ha='center', va='center', fontsize=18, fontweight='bold',
                 bbox=dict(boxstyle='round,pad=0.8', facecolor='lightblue', alpha=0.7))

    # Middle: Feature contributions (positive on right, negative on left)
    ax_contrib = fig.add_subplot(gs[1])

    # Combine all features for plotting
    all_features_plot = negative_features + positive_features
    feature_names_plot = [f[0] for f in all_features_plot]
    contributions_plot = [f[1] for f in all_features_plot]

    # Create horizontal bar chart
    colors = ['#3498db' if c < 0 else '#e67e22' for c in contributions_plot]
    y_pos = np.arange(len(feature_names_plot))

    bars = ax_contrib.barh(y_pos, contributions_plot, color=colors, alpha=0.7, edgecolor='black')
    ax_contrib.set_yticks(y_pos)
    ax_contrib.set_yticklabels(feature_names_plot, fontsize=10)
    ax_contrib.set_xlabel('Contribution to Prediction', fontsize=12, fontweight='bold')
    ax_contrib.axvline(x=0, color='black', linewidth=1.5)
    ax_contrib.grid(axis='x', alpha=0.3)

    # Add value labels on bars
    for i, (bar, val) in enumerate(zip(bars, contributions_plot)):
        x_pos = val + (0.01 if val > 0 else -0.01)
        ha = 'left' if val > 0 else 'right'
        ax_contrib.text(x_pos, i, f'{val:.3f}', va='center', ha=ha, fontsize=9, fontweight='bold')

    # Add legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#e67e22', alpha=0.7, label='Increases Prediction'),
        Patch(facecolor='#3498db', alpha=0.7, label='Decreases Prediction')
    ]
    ax_contrib.legend(handles=legend_elements, loc='lower right', fontsize=10)

    # Bottom: Feature-value table
    ax_table = fig.add_subplot(gs[2])
    ax_table.axis('off')

    # Get feature values for this instance
    feature_values = []
    for feat_name, contrib in all_features_plot[:8]:  # Show top 8
        # Extract just the feature name (before the comparison operator)
        clean_feat_name = feat_name.split('<=')[0].split('>')[0].strip()
        # Get the actual value from the instance
        if clean_feat_name in all_features:
            feat_idx = all_features.index(clean_feat_name)
            feat_val = instance[feat_idx]
            feature_values.append([clean_feat_name, f'{feat_val:.2f}'])

    # Create table
    table_data = [['Feature', 'Value']] + feature_values
    table = ax_table.table(cellText=table_data, cellLoc='left', loc='center',
                           colWidths=[0.6, 0.4])
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 2)

    # Color code the table rows based on contribution
    for i in range(1, len(table_data)):
        feat_name = table_data[i][0]
        # Find if this feature has positive or negative contribution
        is_positive = any(feat_name in f[0] for f in positive_features)
        color = '#ffe6cc' if is_positive else '#cce6ff'  # Light orange or light blue
        table[(i, 0)].set_facecolor(color)
        table[(i, 1)].set_facecolor(color)

    # Header styling
    table[(0, 0)].set_facecolor('#34495e')
    table[(0, 1)].set_facecolor('#34495e')
    table[(0, 0)].set_text_props(weight='bold', color='white')
    table[(0, 1)].set_text_props(weight='bold', color='white')

    plt.suptitle(f'LIME Explanation - {pos} Player', fontsize=16, fontweight='bold', y=0.98)
    plt.tight_layout()
    plt.show()

    # Show top features in text
    print(f"\n[{pos}] Top 5 Contributing Features:")
    print(f"{'Feature Condition':<40} {'Contribution':>15}")
    print("-" * 55)
    for feature, contribution in feature_contributions[:5]:
        print(f"{feature:<40} {contribution:>15.4f}")

print("\n[3/3] Position-specific LIME analysis complete!")

#==============================================================================
# CELL: INFERENCE FUNCTION
#==============================================================================
print("\n" + "="*80)
print("INFERENCE FUNCTION")
print("="*80)

def predict_player_points(df, player_name, gameweek):
    """
    Predicts upcoming total points for a player at a specific gameweek.

    This function mirrors the training pipeline:
    1. Extracts player's historical data from the dataset
    2. Calculates rolling features (weighted_form, goals_last_4, etc.)
    3. Extracts current gameweek features
    4. Encodes and scales features
    5. Makes prediction

    Parameters:
    -----------
    df : pandas.DataFrame
        The complete dataset with all players and gameweeks
    player_name : str
        Name of the player (must match 'name' column in df)
    gameweek : int
        The gameweek number to predict for

    Returns:
    --------
    str : Natural language prediction with player stats
    """

    # ========================================================================
    # STEP 1: VALIDATE INPUT
    # ========================================================================

    # Check if player exists
    if player_name not in df['name'].values:
        return f"Error: Player '{player_name}' not found in dataset."

    # Get all data for this player
    player_df = df[df['name'] == player_name].sort_values('GW').reset_index(drop=True)

    # Check if gameweek exists for this player
    if gameweek not in player_df['GW'].values:
        return f"Error: Gameweek {gameweek} not found for player '{player_name}'."

    # Get current gameweek index
    current_gw_idx = player_df[player_df['GW'] == gameweek].index[0]

    # Check if we have enough history (need at least 4 previous gameweeks)
    if current_gw_idx < 4:
        return f"Error: Not enough historical data for {player_name} at GW {gameweek}. Need at least 4 previous gameweeks."

    # ========================================================================
    # STEP 2: EXTRACT HISTORICAL DATA (last 4 gameweeks)
    # ========================================================================

    history = player_df.iloc[current_gw_idx-4:current_gw_idx]
    current_gw_data = player_df.iloc[current_gw_idx]

    # ========================================================================
    # STEP 3: CALCULATE ROLLING FEATURES (same as training pipeline)
    # ========================================================================

    # Weighted form (last 4 GWs with decreasing weights)
    recent_points = history['total_points'].values
    weights = [0.4, 0.3, 0.2, 0.1]  # Most recent gets highest weight
    weighted_form = sum(p * w for p, w in zip(reversed(recent_points), weights))

    # Goals and assists in last 4 GWs
    goals_last_4 = history['goals_scored'].sum()
    assists_last_4 = history['assists'].sum()

    # Minutes statistics
    minutes_list = history['minutes'].values
    minutes_avg_last_4 = minutes_list.mean()
    minutes_stability = 1 - (minutes_list.std() / (minutes_avg_last_4 + 1))

    # Clean sheet rate
    cs_last_4 = history['clean_sheets'].sum()
    cs_rate_last_4 = cs_last_4 / 4

    # ========================================================================
    # STEP 4: EXTRACT CURRENT GAMEWEEK FEATURES
    # ========================================================================

    creativity = current_gw_data['creativity']
    influence = current_gw_data['influence']
    threat = current_gw_data['threat']
    position = current_gw_data['position']
    was_home = current_gw_data['was_home']

    # ========================================================================
    # STEP 5: CREATE FEATURE DATAFRAME
    # ========================================================================

    features_dict = {
        'creativity': creativity,
        'influence': influence,
        'threat': threat,
        'weighted_form': weighted_form,
        'goals_last_4': goals_last_4,
        'assists_last_4': assists_last_4,
        'minutes_avg_last_4': minutes_avg_last_4,
        'minutes_stability': minutes_stability,
        'cs_rate_last_4': cs_rate_last_4,
        'position': position,
        'was_home': was_home
    }

    input_df = pd.DataFrame([features_dict])

    # ========================================================================
    # STEP 6: ENCODE POSITION (same as training)
    # ========================================================================

    try:
        input_df['position'] = le.transform([position])[0]
    except ValueError:
        return f"Error: Invalid position '{position}'. Must be one of: {list(le.classes_)}"

    # ========================================================================
    # STEP 7: SCALE FEATURES (same scaler as training)
    # ========================================================================

    input_scaled = scaler.transform(input_df)

    # ========================================================================
    # STEP 8: MAKE PREDICTION
    # ========================================================================

    prediction = model.predict(input_scaled, verbose=0)[0][0]

    # ========================================================================
    # STEP 9: FORMAT OUTPUT AS NATURAL LANGUAGE
    # ========================================================================

    team = current_gw_data.get('team_x', 'Unknown Team')
    opponent = current_gw_data.get('opp_team_name', 'Unknown Opponent')
    home_away = "HOME" if was_home else "AWAY"
    actual_points = current_gw_data.get('upcoming_total_points', 'N/A')

    output = f"""
╔══════════════════════════════════════════════════════════════╗
║          FANTASY PREMIER LEAGUE POINTS PREDICTION            ║
╚══════════════════════════════════════════════════════════════╝

Player: {player_name} ({team})
Gameweek: {gameweek} | Opponent: {opponent} ({home_away})

PREDICTED POINTS: {prediction:.2f}
{f'ACTUAL POINTS: {actual_points:.2f}' if actual_points != 'N/A' else ''}

Match Context:
   Position: {position}
   Venue: {home_away}
   Recent Form: {weighted_form:.2f}

Recent Performance (Last 4 GWs):
   Goals: {int(goals_last_4)}
   Assists: {int(assists_last_4)}
   Avg Minutes: {minutes_avg_last_4:.1f}
   Clean Sheet Rate: {cs_rate_last_4:.2%}

FPL Metrics:
   Creativity: {creativity:.1f}
   Influence: {influence:.1f}
   Threat: {threat:.1f}
"""

    return output


print("✓ Inference function created!")
print("\nThe function works with your dataset:")
print("   • Takes: (df, player_name, gameweek)")
print("   • Extracts player's historical data from dataset")
print("   • Calculates rolling features automatically")
print("   • Applies same preprocessing as training")
print("   • Returns natural language prediction")

print("\n" + "="*80)
print("INFERENCE FUNCTION DEMONSTRATIONS")
print("="*80)

# Get some example players from the dataset
example_players = df.groupby('position')['name'].first()

print("\nDemonstrating predictions for different positions...")

# Example 1: Forward
if 'FWD' in example_players.index:
    fwd_name = example_players['FWD']
    fwd_gws = df[df['name'] == fwd_name]['GW'].values
    if len(fwd_gws) >= 5:
        example_gw = fwd_gws[4]  # Use 5th gameweek (has 4 previous GWs)
        print(f"\n[Example 1: FORWARD - {fwd_name}]")
        print(predict_player_points(df, fwd_name, example_gw))

# Example 2: Midfielder
if 'MID' in example_players.index:
    mid_name = example_players['MID']
    mid_gws = df[df['name'] == mid_name]['GW'].values
    if len(mid_gws) >= 5:
        example_gw = mid_gws[4]
        print(f"\n[Example 2: MIDFIELDER - {mid_name}]")
        print(predict_player_points(df, mid_name, example_gw))

# Example 3: Defender
if 'DEF' in example_players.index:
    def_name = example_players['DEF']
    def_gws = df[df['name'] == def_name]['GW'].values
    if len(def_gws) >= 5:
        example_gw = def_gws[4]
        print(f"\n[Example 3: DEFENDER - {def_name}]")
        print(predict_player_points(df, def_name, example_gw))

# Example 4: Goalkeeper
if 'GK' in example_players.index:
    gk_name = example_players['GK']
    gk_gws = df[df['name'] == gk_name]['GW'].values
    if len(gk_gws) >= 5:
        example_gw = gk_gws[4]
        print(f"\n[Example 4: GOALKEEPER - {gk_name}]")
        print(predict_player_points(df, gk_name, example_gw))

print("\n" + "="*80)
print("USAGE EXAMPLES")
print("="*80)
print("\n# Predict for a specific player and gameweek:")
print("prediction = predict_player_points(df, 'Mohamed Salah', 10)")
print("\n# The function will:")
print("  1. Find 'Mohamed Salah' in the dataset")
print("  2. Get his data for gameweeks 6-9 (history)")
print("  3. Calculate rolling features from that history")
print("  4. Get his features for gameweek 10")
print("  5. Apply preprocessing and make prediction")

print("\n" + "="*80)
print("✅ MILESTONE 1 COMPLETE")
print("="*80)
print("\nDeliverables:")
print("  ✓ Data cleaning and preprocessing")
print("  ✓ Form calculation")
print("  ✓ Data engineering questions answered")
print("  ✓ Feature engineering (11 optimized features)")
print("  ✓ FFNN model trained and evaluated")
print("  ✓ Position-specific SHAP analysis (FWD, MID, DEF, GK)")
print("  ✓ Position-specific LIME analysis (FWD, MID, DEF, GK)")
print("  ✓ Inference function with demonstrations")